export default [
	"#[TokenSymbol] is our future of investment",
	"About to cross to the other side of the #[TokenSymbol]",
	"We're still in the middle of the river of #[TokenSymbol]",
	"Everyday we gives full support to #[TokenSymbol]",
	"Let keep them flying always and all over the world  with  #[TokenSymbol]",
	"Our greatest community ever #[TokenSymbol]",
	"Who else ready for today work with #[TokenSymbol]",
	"Let us make another beautiful achievement for ourselves and also for this grow of #[TokenSymbol] as well",
	"This #[TokenSymbol] community will continue growing",
	"We're welcome to another beautiful day with #[TokenSymbol]",
	"I love you all as I love #[TokenSymbol]",
	"Always remember your determination for #[TokenSymbol]",
	"Let keep working towards achievement",
	"Dream about #[TokenSymbol]",
	"Very good at me with #[TokenSymbol]",
	"Always remember where you're going to with #[TokenSymbol]",
	"Let related to #[TokenSymbol]",
	"We're all here to spend time with #[TokenSymbol]",
	"Wonder shall never end in this community #[TokenSymbol]",
	"#[TokenSymbol] has changed all my immune system",
	"My head is full of #[TokenSymbol]",
	"I abandon Facebook,WhatsApp Instagram and focus with #[TokenSymbol]",
	"This community makes me forgot other social media always here with them",
	"I am like a son under #[TokenSymbol]",
	"If am sleeping I think dream about #[TokenSymbol]",
	"Already addicted to #[TokenSymbol]",
	"That's way I love stay with #[TokenSymbol] always here every second",
	"Even me #[TokenSymbol] is my icon",
	"Good decision to #[TokenSymbol]",
	"To last city and rest with #[TokenSymbol] as our future plan",
	"Always supporting #[TokenSymbol]",
	"Our observation with #[TokenSymbol] is for our future purpose with #[TokenSymbol]",
	"#[TokenSymbol] is our insurance everlasting",
	"#[TokenSymbol] is the biggest deal in the Crypto market",
	"Let soar instead of flying #[TokenSymbol] is here to stay forever and I'm very sure about it",
	"I'm so much ready for this and I'm very sure i will make it to the top of #[TokenSymbol]",
	"I'm supporting [TokenSymbol] with all i got",
	"Let keep supporting [TokenSymbol]",
	"We can make this happen now. Let retweet #[TokenSymbol]",
	"Let support [TokenSymbol] now and forever",
	"Let go guys we can make this happen now",
	"Hope you're ready to stay at the moon with [TokenSymbol] because we are never coming back to earth after getting to the moon",
	"[TokenSymbol] is the winning team",
	"We can make this work for us all",
	"I'm ready to continue giving my sincere support and showing my true love for this great project",
	"Let move to the next level together",
	"Thanks for believing in [TokenSymbol]",
	"[TokenSymbol] it the real deal and it's going to be here forever",
	"#[TokenSymbol] to the moon am waiting who is coming with me",
	"We are ready for a massive Price pump. Get ready let do this",
	"[TokenSymbol] is our only hope for a great future",
	"Let go higher as a good team #[TokenSymbol]",
	"Let unite and do this",
	"I believe in this project",
	"Let keep supporting [TokenSymbol]",
	"$[TokenSymbol] is pumping every day",
	"$[TokenSymbol] is our hope",
	"Let make this project greater",
	"Really bright for everyone here. We're all winners",
	"Hope you trust $[TokenSymbol]",
	"Buy enough $[TokenSymbol] now and hold",
	"$[TokenSymbol] is here to help  a lot of people",
	"$[TokenSymbol] help my colleagues",
	"$[TokenSymbol] is here to stay",
	"Sun rise give bless everyday like #[TokenSymbol] give us joy",
	"#[TokenSymbol] way is the way to success",
	"Be kind to your self and with team",
	"Never relent your  spirit to win",
	"Keep moving toward determination with #[TokenSymbol]",
	"All always keep guided with the rules",
	"I wish everyone big win at end of this project",
	"[TokenSymbol] movement, and progress is my progress 👍",
	"Let keep maintaining our position here",
	"Be happy for our $[TokenSymbol]",
	"Don't rush at all work gently and win",
	"Let's keep a healthy environment for [TokenSymbol]",
	"We're still moving well with the current pace",
	"Don't make any mistakes to go against the rules",
	"Let the world 🌎 know that [TokenSymbol] is the movement🚀",
	"Let's continue giving it out best, together we can make it happen",
	"I keep going and growing with the team",
	"Let's work together now so we can win together",
	"Keep support and encouraging my word on #[TokenSymbol]",
	"Love for $[TokenSymbol] 🚀 is propelling my support",
	"#[TokenSymbol] I will support you till the end",
	"The achievement and advancement of $[TokenSymbol] is our win as a community. The teams need our voice to be loud about it",
	"Let every hands keep typing for success",
	"Don't never lose your hopes to win",
	"It's good being part of this development",
	"Never give up to achieve your goals and continue to fully support the [ProjectName] project",
	"#[TokenSymbol] with give surely give me rejoice",
	"Thank you, although we don't know each others but I really appreciate you keep moving with #[TokenSymbol]",
	"Be kind to yourself and with team and others",
	"#[TokenSymbol] way is the way to success",
	"$[TokenSymbol] is here to help people",
	"It's really wonderful being part of this great project",
	"I want to fill my wallet with $[TokenSymbol]",
	"They are moving to greater heights, up [TokenSymbol] to the moon",
	"We are here supporting each other",
	"Let's do something worthwhile now and give our support",
	"Nothing is free everywhere, but #[TokenSymbol] is giving us tokens for time and effort we provide here",
	"Let's target the top spot",
	"Let's not forget to preach [TokenSymbol] to the world",
	"Your support is very passionate to #[TokenSymbol]",
	"yes we can do better than before and we'll still keep doing our best",
	"If you type meaningful messages to support the project",
	"If you want to win, keep your support until the end!",
	"If you know #[TokenSymbol] keep in mind #[TokenSymbol] also know you",
	"Let keep dreaming about our goal with #[TokenSymbol]",
	"[TokenSymbol] is a great project. Price soon go up",
	"Take your time to read the whitepaper and you will find [TokenSymbol] is a very fascinating project",
	"Community is go to be impacted with #[TokenSymbol]",
	"Invest and stake so you can live a good life",
	"We will not rest until success is achieved",
	"[TokenSymbol] is speedily rushing up to take their position where they belong",
	"Let's do much cherish with #[TokenSymbol]",
	"The moment we've all been waiting for is here now",
	"Let's keep pushing them with our team effort for greater things we shall do as a team",
	"Best community here never seen anywhere",
	"Let's all continue meet here as we keep supporting [TokenSymbol] and their great project",
	"Hold your position. The bags are about to get filled",
	"I wish I knew what I know now right now from the beginning of this event",
	"All the guys here are warrior. They fighting on this battle on the time",
	"Show more love for the project and the dev team guys",
	"We must do our best to keep this community alive",
	"Pushing forward more guys",
	"Keep fighting to support [TokenSymbol] project and don't lose hope",
	"Im try hard to prove my love for [TokenSymbol]",
	"Lets do the miracle",
	"Keep the spirit of this community",
	"If u are feel tired then rest to recharge more energy",
	"Typing more but dont force yourself too hard",
	"My fingers are becoming more active and gain more muscles now",
	"Be loyal and support [TokenSymbol] with u whole heart",
	"We are the best community ever",
	"[TokenSymbol] community feel like family to me",
	"Dont rush just enjoy the progress",
	"Follow [ProjectName] on every social media",
	"We will all win at the end of the day",
	"Drink more coffee to stay active here",
	"You guys are doing really well",
	"Learn English just y typing here",
	"Don't loose focus now. Stay healthy",
	"Wow we all trust [TokenSymbol]",
	"I'm dreaming about the day [TokenSymbol] become a giant crypto project",
	"Our mission are never stop support [TokenSymbol]",
	"Always thinking about [TokenSymbol] even in my sleep",
	"Lets move this project forward",
	"The hard work will pay off in the long run",
	"Your best long time investment is [TokenSymbol]",
	"Crypto currency will take over the world and one of the biggest is [TokenSymbol]",
	"[TokenSymbol] will break all the barrier to obtain success",
	"Invest in [TokenSymbol] for u better future",
	"[TokenSymbol] is the real deal for me",
	"This project is one in a million",
	"This project will be shine the sun",
	"I guess so many people spent a full time to support [ProjectName] here",
	"Hold your [TokenSymbol], don't sell it too fast.",
	"With teamwork everything will be possible",
	"[TokenSymbol] is my belove. I will support it no matter what",
	"Laziness doesn't work here. You get what you are working for",
	"Go go go keep support more for [TokenSymbol]",
	"This support is so hard to maintain. Only the strongest can survive",
	"[TokenSymbol] is a life time investment",
	"Keep hold and buy more [TokenSymbol]",
	"I'm here to show my love for [TokenSymbol]",
	"We are here to win. Lets join me in the winner list",
	"[TokenSymbol] is a hidden gem for sure. Buy it before too late",
	"[TokenSymbol] is going to the moon soon. I need to save up money and buy more",
	"Lots of people are here to participate",
	"Be active but don't forget to stay in the rule",
	"This is definitely a very good and this project has its own characteristics",
	"Just relax and be active more. This friendly community will help u in the top",
	"Dont stop for what ever reason. Support [TokenSymbol] more",
	"If you tired, take rest and come again with full refresh",
	"[TokenSymbol] is my belove. The true love of my life",
	"Assemble! [ProjectName] supporters",
	"There's always a great news with [TokenSymbol]",
	"The moon is not ready for [TokenSymbol] army yet",
	"If u are have [TokenSymbol]. Just keep buy more and hold it",
	"Make the community stronger guys",
	"We are here to support this awesome community",
	"Let's keep the vibe positive and always stay strong",
	"My love for [TokenSymbol] and this community is can't be measured",
	"Nothing interest me anymore only [TokenSymbol]",
	"Keep believe and dont stop support [TokenSymbol]",
	"The more you support [TokenSymbol] the more benefit you gain",
	"There is a plenty time to reach the top",
	"Keep in touch more with the project",
	"[TokenSymbol] is worth for the fight",
	"What else do we have if not to support this team",
	"[TokenSymbol] will be a top crypto coin by then",
	"Im saving money to buy more [TokenSymbol]",
	"[ProjectName] give us so much energy",
	"We will go to the moon soon",
	"We will bounce back to ath soon enough",
	"It's quite tiring but I hope and pray we all make it to the final lap",
	"Dont stop and never ever look back guy",
	"Buy [TokenSymbol] before it too late mate",
	"Keep you royal and support [TokenSymbol] with you whole heart",
	"Tweet more about [TokenSymbol] guys",
	"Hope [TokenSymbol] will be listed on every platform",
	"Type more and more. Show your love for [TokenSymbol]",
	"The market is unpredictable but just keep believe in [TokenSymbol]",
	"This support is hard to be consistent. I must try harder",
	"[ProjectName] will change my life",
	"We can win this together. [ProjectName] is the real deal",
	"I love this project like it's my own company and I'm gonna enjoy it's success now and more in the future",
	"We have to move together as a community",
	"The more you support the better this community become",
	"If u are have [TokenSymbol]. Just keep buy more and hold it",
	"I believe in this movement🚀",
	"The most active community I ever experienced",
	"There is no doubts about #[TokenSymbol] success in the crypto world",
	"Nice project and I look forward to the growth and success of this project ✨",
	"The #[TokenSymbol] team are more advanced in there dealings",
	"$[TokenSymbol] we can go up",
	"We don't sleep till we are satisfied with the support we've given for the day",
	"Let's make the best of this opportunity",
	"We give our best to the betterment of $[TokenSymbol]",
	"Come on go up to the higher lvl",
	"[TokenSymbol] 🚀 is definitely gonna reshape the future of crypto",
	"Keep chatting here for an assurance of winning",
	"It's only in chatting here that we win, let's keep typing",
	"Go steadly and be careful. Keep helping other member to make this great community more good",
	"I love this community",
	"You guys are doing really well. Keep it up",
	"Greatness is what we'll derive💪",
	"Keep supporting [TokenSymbol] and don't lose hope",
	"$[TokenSymbol] also has a telegram member who is very compact and always supports him towards success.",
	"I cannot be discouraged, I have to type to meet up",
	"Wait for the price of $[TokenSymbol] to rise then you will enjoy the results",
	"I feel Proud to be a part of [ProjectName] community",
	"$[TokenSymbol] is the best token to hold",
	"Buy buy buy $[TokenSymbol] is rising",
	"Right, this project not for going down",
	"It's always good to push with my friends in [ProjectName] community👍",
	"I love all the members of this group",
	"No time to wasted on other thing. Just focus and talk more about [TokenSymbol]",
	"No need to be pessimistic keep try harder mate",
	"[TokenSymbol] is a project with a solid background.",
	"In [TokenSymbol] we trust. Make [TokenSymbol] great",
	"We all wanna learn more about this project and share our knowledge with each other",
	"If u spend all the time here u can make it",
	"$[TokenSymbol] touched my heart until I fell in love with $[TokenSymbol] 😍",
	"Dont stop for what ever reason. Support [TokenSymbol] more",
	"We should support all [ProjectName] project",
	"We are going to the moon. Nothing can't stop us",
	"I think im too late but im support this project anyway",
	"Solid project of [TokenSymbol] with a great community inside of it",
	"[TokenSymbol] is my belove. I will support it no matter what",
	"We should be proud to be a part of this great project with $[TokenSymbol]",
	"The hardest part is keep your position, keep supporting",
	"Keep supporting [ProjectName], mate",
	"No one can stop #[TokenSymbol] reaching the moon",
	"The very best, the most unified and tighest crypto community",
	"[TokenSymbol] carry me to the moon, carry me to the mars 🚀",
	"We know we can do this of course",
	"My dream is [ProjectName] can go to the moon with us",
	"We are champion. [TokenSymbol] is a champion too",
	"Keep hold your [ProjectName]",
	"#[TokenSymbol] is the best project I found",
	"No one ever could predict the #[TokenSymbol] future, it would be great beyond imagination",
	"I signed to be a supportive member of [TokenSymbol] community",
	"We can definitely become $[TokenSymbol] champion",
	"Everyone start somewhere keep increase your xp",
	"[TokenSymbol] 🚀 frequency is superb",
	"There's no limit time to waste",
	"Keep yourself healthy so u can support [TokenSymbol] more",
	"I feel unlimited love for my beloved #[TokenSymbol].",
	"#[TokenSymbol] Is the best way to success your life.",
	"Hold your gem, nope, it's [TokenSymbol]",
	"[TokenSymbol] is absolutely my favorite token",
	"Soon it will catch up some major crypto currency",
	"We are the best at what we do, let's continue to support",
	"Yes I can do it, I can type to the moon with $[TokenSymbol]",
	"Stay motivated and captivating",
	"Someone should tell everyone that $[TokenSymbol] is really great",
	"Fight for it, and spread #[TokenSymbol] to the world.",
	"Let's then keep on chatting and keep up the good work",
	"Don't let us forget to keep moving and supporting this project",
	"Everybody is going to smile at the end because of [TokenSymbol]",
	"It's really impressive the way we are uniformly supporting this project",
	"I need more [ProjectName] in my life, to secure my future",
	"Let's use community effort, let's use group effort to move them forward",
	"I'm thinking what we can do as a #[TokenSymbol] army to stand out from the rest",
	"Everyone let's keep supporting [TokenSymbol] now let's keep investing and holding",
	"Lets all stay safe and follow the rules. They are meant to guide us",
	"I'm committed to this project and her community",
	"[TokenSymbol] is the project we need to prepare our future, to have financial security",
	"#[TokenSymbol] will continue to win non-stop",
	"Let's continue typing and doing what we need to do to support them get to the level they want",
	"Let's appreciate everyone's hardwork here",
	"Tweet about #[TokenSymbol] make us trending",
	"Let's wait and see how this project will flourish and skyrocket up",
	"Let's be happy because we are really supporting a great project",
	"#[TokenSymbol] is a next future coin now",
	"It's good being part of this development",
	"Keep your spirit. Go ahead with positive mind",
	"Keep burning your typing with #[TokenSymbol] and a healthy discussion as always",
	"Never give up to achieve your goals and continue to fully support the #The[ProjectName] project",
	"We're all the hero leaders and #[TokenSymbol] is the icon of the recon",
	"Let join hand together and support ourselves",
	"We definitely know that $[TokenSymbol] has a lot of supporters in this place",
	"If we all support $[TokenSymbol] we will win together",
	"I want $[TokenSymbol] to always go at the top",
	"$[TokenSymbol] to make crypto market always grow",
	"I want to fill [ProjectName] my wallet with every single $[TokenSymbol]",
	"$[TokenSymbol] is here to help people",
	"Let's not forget to preach [TokenSymbol] to the world",
	"With our believe we can win and support #[TokenSymbol]",
	"We are going to trend all social platforms",
	"Let keep going guys we can make #[TokenSymbol] the best coin ever",
	"To the last city and rest with #[TokenSymbol] as our future plan",
	"Make a shirt with [TokenSymbol] logo in it, show [TokenSymbol] in your works",
	"Don't stop supporting [TokenSymbol] because a worth it project",
	"Wait for a while. Our [TokenSymbol] will reach at moon soon.",
	"I will keep supporting #[TokenSymbol] even if i don't win this chatting",
	"I give my all to this project because the team, concept and community are the best",
	"You rightly say that #[TokenSymbol] is the best crypto on Earth.",
	"We need to motivate each others",
	"I'm making effort to keep my support and typing only on [TokenSymbol]",
	"We're [TokenSymbol] 🚀 army. We got one another to the moon",
	"Seriously, I'm impressed with #[TokenSymbol]",
	"There are lot of opportunity in the crypto world especially for [TokenSymbol] to rise",
	"We are all the winners, losing or winning doesn't matter.",
	"We have to keep supporting [ProjectName]",
	"Let's run fast with [TokenSymbol] together",
	"I'm enjoying chatting here, maybe I have #[ProjectName] syndrome",
	"I am very happy and excited to participate in this event, very good project for the future",
	"Run speedily with #[TokenSymbol]",
	"Seems to me some people are trekking to the moon already",
	"What are your prediction for #[TokenSymbol] price will be at the end of the 2021?",
	"Keep supporting [ProjectName], I'm sure you will never be disappointed.",
	"I have been with #[TokenSymbol] from the start and I'll be with them till the end",
	"Chating in here can also be fun",
	"It's a good investment to buy [TokenSymbol], isn't it?",
	"Keep typing with don't forget to folow [TokenSymbol] social media",
	"Holding [TokenSymbol] in your wallet is the best step to take",
	"We should build a community that follows rules",
	"Make the best decision of your life and invest in #[TokenSymbol]. Now or never",
	"An important way to stay in [ProjectName] is to take a rest if you're tired",
	"it such a blessing to be here with #[TokenSymbol] community",
	"It will be a huge success, if we have full support of [ProjectName] community",
	"Never lose your motivation to support #[TokenSymbol]",
	"[ProjectName] your spirit like this project #The[ProjectName]",
	"[ProjectName] has come to give us a better life",
	"There is no doubt in me to fully support #The[ProjectName]",
	"Let's go to the moon with $[TokenSymbol]",
	"Let's raise your spirit and [ProjectName] your spirit",
	"The city all know that the city here is a big family of [TokenSymbol]",
	"#[ProjectName] is very good for long term investment",
	"Never give up when providing information about #[ProjectName]",
	"Burn your finger on your phone screen to keep typing about #[ProjectName]",
	"Never forget to give support in this group every day",
	"We will take $[TokenSymbol] to the moon.. let's spend our money to invest on $[TokenSymbol]",
	"We are always here to support the [TokenSymbol] project to always be the leading project",
	"I fully believe in the #The[ProjectName] project",
	"#[TokenSymbol] team you have people willing to do anything for the project to succeed",
	"Let's keep working with [TokenSymbol] to execute their plans in the project",
	"Don't forget to take care of your health, friends. because it's so important. $[TokenSymbol] still needs you",
	"We need a lot of social media to support this project better and get to know more people",
	"We are waiting for $[TokenSymbol] to print a new price record later",
	"Ignite our spirit for $[TokenSymbol]",
	"We will be whales in the future",
	"$[TokenSymbol] is an excellent project in the development of a blockchain-based crypto currency infrastructure",
	"Don't forget to read the pinned message in the #The[ProjectName]",
	"#[TokenSymbol] pump is active soon",
	"People will buy #[TokenSymbol] when it is 100 times more expensive than it is today.",
	"More movement and progress here",
	"[TokenSymbol] community built with love",
	"#[TokenSymbol] is like the Internet of the early 20s, and today we all use it",
	"Everyone gets #[TokenSymbol] at the price they deserve",
	"#[TokenSymbol] is the strongest money we have ever had.",
	"#[TokenSymbol] is a digital gold",
	"Buy #[TokenSymbol] It's never too late to be honest",
	"#[TokenSymbol] always help you to success your life",
	"We all know #[TokenSymbol] could make a difference in crypto world and our lives",
	"Stay support #[TokenSymbol] bruhh, this good project",
	"We are here to promote #[TokenSymbol]",
	"We are doing our best to enlarge the [TokenSymbol] family",
	"I cant wait till #[TokenSymbol] is listed everywhere in listable platform",
	"Great one #[ProjectName] team",
	"The community of great minds #[ProjectName]",
	"[TokenSymbol] is up and rushing to get to the moon",
	"I found [TokenSymbol] so interesting that I talk about it in my dreams",
	"Keep supporting and giving love to [ProjectName] team",
	"Keep following the rules as they're really important",
	"I hope you all spending some time taking care of yourself and recharging yourself",
	"Keep supporting [ProjectName] as always, we aim to be at the top.",
	"It will be a huge success, if we have all the support of member of [ProjectName] community",
	"We can move together as a community and a family",
	"$[TokenSymbol] every day make you rich.",
	"Keep moving and keep focus",
	"I'm glad to participate in this event",
	"I try to dedicate myself to [TokenSymbol].",
	"Support [TokenSymbol] every day until whenever",
	"We will win together, keep chatting and enjoy time in [TokenSymbol] community.",
	"Its time to make the market boom with #[TokenSymbol]",
	"Let's go to the moon $[TokenSymbol]",
	"Don't forget to hold #[TokenSymbol] ❤️😍  we will be success by #[TokenSymbol]",
	"Those who are ready to win are ready to reward",
	"$[TokenSymbol] is an important innovation in the history world since the Internet.",
	"This is a household name in [TokenSymbol].",
	"$[TokenSymbol] cannot be acquired for free, we need effort. Let us support them",
	"Incredible project are hard to come by",
	"$[TokenSymbol] is cryptocurrency of the people",
	"Determination is most important in anything you're doing or working on",
	"[TokenSymbol] is coming, for the moon please be ready",
	"[TokenSymbol] taking over the market",
	"Impressive #[TokenSymbol] dev team and an great project with a great community",
	"I love anyone who loves [TokenSymbol]",
	"We have nowhere to go than [ProjectName] community",
	"I think [TokenSymbol] project great project",
	"Will earn [TokenSymbol] more and more in the future",
	"Decentralization has brought more goodies",
	"Tell other projects, they can't beat the idea that birthed #[TokenSymbol]",
	"We are sailing to the moon",
	"Let's make it to the top together",
	"Let's make it a habit to always tell folks of [TokenSymbol]",
	"Stay in [ProjectName], stay motivated, stay focused",
	"Nothing can withstand our sailing with [TokenSymbol]",
	"Keep the hope alive. #The[ProjectName] rules",
	"We can achieve anything with [TokenSymbol]",
	"We are focused. [TokenSymbol] is the goal",
	"$[TokenSymbol] is ready to go to the moon and, stay there",
	"The market is uptrend now. I will buy more [TokenSymbol]. My salary will come soon",
	"Wait for $[TokenSymbol] listing in the next few markets. and $[TokenSymbol] prints its new price",
	"We hope the price of $[TokenSymbol] goes up from now so that other people want to invest in the $[TokenSymbol] project",
	"With [TokenSymbol], we are ready to go anywhere",
	"Everyone here are winners. [TokenSymbol] will make us winners",
	"#[TokenSymbol] will always be a success, success will never end with #[TokenSymbol]s",
	"We are the strongest community in the crypto galaxy",
	"No other project can be so reliable as this",
	"#[TokenSymbol] is really special, never seen anything like it honestly",
	"Full of support for [ProjectName] and ready to go",
	"Make sure you hold [TokenSymbol] as much of it as possible.",
	"I'm desperately in love with #[TokenSymbol]s",
	"Stay tune and waiting for good news",
	"I've been rewarded with a great community of friends",
	"Thinking about [TokenSymbol] day and night",
	"Good and promising future with [TokenSymbol]",
	"It's a perfect plan to execute at this point in time",
	"Everyone has the same opportunity to win [TokenSymbol]",
	"[TokenSymbol] has a best purpose, this is a good project guys keep support for this",
	"Never give up support project $[TokenSymbol]",
	"Keep the spirit until the event ended",
	"#[TokenSymbol] has an innovative value",
	"Let us suggest ideas, schemes and policies that can make #[TokenSymbol] better",
	"#[TokenSymbol] makes us fortune that will make us all retire early",
	"We need to look out for each other as [ProjectName] family",
	"We all getting into that rocket together",
	"The rewards are great, nothing comes to the lazy, only those willing to make sacrifices to achieve",
	"Honestly the #[TokenSymbol] community is unreal, with this amount of support",
	"We all a team let's support each other",
	"Nothing good comes easy bro, keep at it don't relent, [TokenSymbol] will answer you",
	"Keep your spirit you all, we can do it, but dont forget not too force yourself too hard",
	"Dont lose your motivation, and keep your consistency in supporting this project",
	"Don't expect me to stop loving $[TokenSymbol] because I love #[ProjectName] more than myself",
	"We all should be the winner. If we do a hardwork",
	"The dev of $[TokenSymbol] is working really harf yet still close to the community",
	"The community is really active and keep growing",
	"We are all glad, to be able to be here and support #[TokenSymbol] team",
	"Just enjoy your time in here, don't get too stressed about this event",
	"Thanks for the community make this project nice and smooth ever",
	"We have to keep supporting $[TokenSymbol], the project is just too good",
	"This is the best crypto community #[TokenSymbol] is the future",
	"$[TokenSymbol] is the reason I started a journey to financial freedom",
	"Just take it easy, everyone will definitely get [TokenSymbol]",
	"Nice people out here who supports each other thanks to $[TokenSymbol]",
	"I'm happy with [TokenSymbol] sharing token easily",
	"Take seats on the rocket of [TokenSymbol] to the moon",
	"Every one have the same motive keep type win maximum prizes [TokenSymbol]",
	"#[ProjectName] has come to make enjoy with you.",
	"Don't know how many messages must be typed from the beginning",
	"Keep going, stay active, we all family here we will help you",
	"We can see that [ProjectName] has very good future prospects",
	"#[TokenSymbol] is awesome forever",
	"Hopefully the price of $[TokenSymbol] goes up",
	"[TokenSymbol] is really going to be king of cryptocurrency",
	"Don't forget to follow twitter #[ProjectName]",
	"Don't forget your coffee to keep you focused while chatting here",
	"[TokenSymbol] is something we should think seriously",
	"The whole world should know, this project and opportunity is too good to pass up",
	"I'am too happy about #[TokenSymbol], even to sleep is hard",
	"It will continue to go up nonstop and will never go down #[TokenSymbol] all the way",
	"#[TokenSymbol] is the most reliable ever, they never fail or go back on their word",
	"Let's go more more more for [TokenSymbol]",
	"I know this and believe [TokenSymbol] will change the way we see tokens",
	"#[TokenSymbol] community, team and project are the best ever",
	"I willl support til the end of time, will never stop supporting #[TokenSymbol]s",
	"$[TokenSymbol] forever will be my number one crypto",
	"Every blessed day here is great blessed from the #[TokenSymbol]",
	"Let's work hard so you can take your postion",
	"#[TokenSymbol] is worth all this never forget, this is a huge opportunity",
	"This shows how great a community we are, #[TokenSymbol] community is the best ever",
	"$[TokenSymbol] is the future lets stand together",
	"For #[TokenSymbol] guys, we are the community and we have to stand together",
	"Lets keep working together and figting to make sure #[TokenSymbol] is as great as it should be",
	"This is really alot to take in, #[TokenSymbol] this can't be true",
	"[TokenSymbol] has many schemes for holders to benefit from",
	"[TokenSymbol] gives power to holders",
	"No doubt that #[TokenSymbol] is best",
	"We are one family $[TokenSymbol] family and we stick together till the end",
	"Keep working hard and I hope everyone winning",
	"[TokenSymbol] community brings myself going in-depth about how amazing this project are",
	"We got a lot of people talking bout [TokenSymbol]",
	"[TokenSymbol] is a natural motivator. You can't get tired",
	"Keep believing and let's make this project bigger.",
	"Keep supporting [ProjectName] and keep discussing about it",
	"Read about [TokenSymbol] for the future",
	"We're glad to found [TokenSymbol]",
	"To achieve success, we need to support [TokenSymbol] in long term.",
	"The #[TokenSymbol] team have all positive attributes in surplus",
	"We will go to the moon with [TokenSymbol] soon. Prepare your [TokenSymbol] guys. Dont be late",
	"Long way to go to reach the destination, but I will keep continue to support",
	"Dont forget to tweet about [ProjectName]",
	"You can read the whitepaper to learn more about #[TokenSymbol]",
	"Token [TokenSymbol] always in my brain",
	"How are you today [TokenSymbol] army?",
	"[TokenSymbol] is have great project and the have  great opportunity to the moon",
	"Hope everyone will win [TokenSymbol] in the end",
	"We stand with and for [TokenSymbol]",
	"[TokenSymbol] need everyone who believe in [TokenSymbol]",
	"It is our job in the community to make [TokenSymbol] better",
	"Everyone want to get reward from [TokenSymbol]",
	"Get your own motivation up",
	"Buy new bag and fill with [ProjectName]",
	"Invested now in [ProjectName] tokens",
	"I wish all the best especially for the dev and team",
	"Keep going! Long way to go but it is fine",
	"We will be on the moon no matter what happen, [TokenSymbol] in our hands now",
	"Take care of our [TokenSymbol]",
	"I'm doing this for #[TokenSymbol] only, forget others",
	"There is plenty of time ahead of us, we could be wherever we want",
	"Forever we will win. This time you win [TokenSymbol] for sure",
	"The Quality and quantity of this group is improving everyday",
	"We are here for each others in [TokenSymbol] brotherhood",
	"We will never know what happens next but we are ready to go with [TokenSymbol]",
	"This is our golden opportunity to make a history",
	"I will show my support to #[TokenSymbol]",
	"[TokenSymbol] for the champion",
	"Moving fast with [TokenSymbol]",
	"I know [TokenSymbol] can do that as well",
	"Stay focused. [TokenSymbol] plan is the best!",
	"Make your [TokenSymbol] worth and shine among the stars",
	"Enjoy the chat, talk about [TokenSymbol] and don't spam, that is all",
	"We could only support to make this group great",
	"If you are tired stop typing. Take care of your health here",
	"$[TokenSymbol] will be the top 100 Cryptocurrency",
	"We are a big family of [TokenSymbol] will always support [TokenSymbol]",
	"Don't save your money let's buy [TokenSymbol]",
	"I will never sell my $[TokenSymbol] my dear",
	"We can make this community the biggest one in all crypto world",
	"I will never tired of supporting $[TokenSymbol]",
	"Actually I'm enjoying to be here with this great community",
	"We should be proud to be a part of this great project with $[TokenSymbol]",
	"Whatever it is, make us proud with you $[TokenSymbol]",
	"I do everything now for my love $[TokenSymbol]",
	"HODL $[TokenSymbol] as long as possible for the future",
	"$[TokenSymbol] amazingly great project in the world that only I know",
	"Forget other Cryptocurrency project. Let's work on this best project",
	"$[TokenSymbol] makes my wallet something valuable",
	"I'm a loyal supporter of $[TokenSymbol]",
	"Everyone will buy $[TokenSymbol] and support wholeheartedly",
	"$[TokenSymbol] has a large community. We must fully support",
	"Let's join forces to keep supporting $[TokenSymbol]",
	"$[TokenSymbol] makes my wallet full of smile",
	"Never sell your $[TokenSymbol] because it will be expensive in time",
	"We work hard and always support $[TokenSymbol]",
	"We are big family $[TokenSymbol]",
	"I want to tell you the $[TokenSymbol] website is really good isn't it?",
	"$[TokenSymbol] has always been my taste. $[TokenSymbol] $[TokenSymbol] my taste",
	"$[TokenSymbol] I believe you will make us rich",
	"[TokenSymbol] is one of the ambitious and extraordinary projects in the future",
	"Wait moment $[TokenSymbol] go the moon",
	"Don't stop your finger and keep support $[TokenSymbol]",
	"$[TokenSymbol] projects are good to invest in",
	"Don't skip this project. Beacause we will to the moon together soon.",
	"Get more reward and keep typing in here",
	"$[TokenSymbol] is the great project on the earth",
	"$[TokenSymbol] has a very strong community",
	"[TokenSymbol] project that everyone is looking forward to",
	"If you keep more [TokenSymbol] in your wallet, then you will be rich in the future",
	"If you pick a moon. Brings [TokenSymbol] so you won't be alone",
	"Let's keep on typing. [ProjectName] your days with [TokenSymbol] to get big profits. [TokenSymbol] to the moon",
	"Hodl your [TokenSymbol] token from now",
	"I support this project until it's big. This community will always provide support for that development",
	"Every day I pass with [ProjectName]. My enthusiasm for this project is growing with the hope that all of us can enjoy the tremendous benefits of [TokenSymbol].",
	"It is possible that [TokenSymbol] can reach $10 in the future",
	"I hope in the near future it will reach a new ATH",
	"I will try my best in the current event. Let's support each other together",
	"My fingers are strong enough today.",
	"An early start is needed to get something big.  When it's too late, everything feels regret. Now it's an early start for [TokenSymbol]",
	"Save this earth with [ProjectName] and make people prosperous",
	"This project is very likely to attract many people in the near future",
	"If there are many who have entered into cooperation contracts with [ProjectName], it will definitely exceed the previous token price",
	"[TokenSymbol] one of the best cryptos, I could tell even though I'm new to crypto.",
	"[TokenSymbol] has been an inspiration in their innovative approaches",
	"I am very happy to be participating in this project",
	"I hope this project will be better in the future and will be the best crypto",
	"[TokenSymbol] has been an inspiration in their innovation in nature and digital",
	"This is community of [ProjectName] very strong team",
	"[TokenSymbol] big plans for the future",
	"We all going to the moon together and #[TokenSymbol] is the rocket we taking to the moon",
	"Always support this project until successful",
	"I would love to invest more in [TokenSymbol]",
	"I'm so addicted to chat about [TokenSymbol]",
	"We all will make it. Its for [TokenSymbol]",
	"I literally need to keep supporting [ProjectName]",
	"A very strong #[TokenSymbol] project, for a better future",
	"Getting more knowledge by being active in chat community.",
	"Keep spirit guys, we as [TokenSymbol] comunity must be strong",
	"Nice to see the community going stronger",
	"Stay safe and healty everyone, don't force yourself to much",
	"I just want to remind you not to forget to tweet anything related to [ProjectName]",
	"The more you know abour [TokenSymbol], the more awesome it will be",
	"[TokenSymbol] is a project with a solid background",
	"[TokenSymbol] is just too good and the dev are working hard",
	"The potential of this project is outstanding",
	"I want [TokenSymbol] to one of the biggest project in the future",
	"[TokenSymbol] HODLers is getting more and more by the time. Especially when this event ends.",
	"i just read more about [TokenSymbol] from their website, turns out [TokenSymbol] is even more amazing",
	"$[TokenSymbol], we need to understand how it works at this level",
	"It's only natural for $[TokenSymbol] to get bigger, the project is just so good",
	"Dont even have a single doubt for [TokenSymbol], thats how good this project is",
	"It's going to be great to have [TokenSymbol] on every platform",
	"The community is really active and keep growing",
	"Keep our support for [TokenSymbol], but health is still no 1 priority",
	"The future is actualy now, thats what [TokenSymbol] to you",
	"You can go to #The[ProjectName] Website page to read some article about [TokenSymbol]",
	"This is truly a test for our consistency to be here",
	"Dont forget to hold your $[TokenSymbol], its easy passive income",
	"Buy it. You will never regret your investment with #[TokenSymbol]",
	"Let keep them flying always and all over the world with #[TokenSymbol]",
	"We sould keep learning about #[TokenSymbol]",
	"We'll go to the moon and beyond, with #[TokenSymbol]",
	"To guys dont forget to read the pinned messages for some recent update",
	"Understanding #[TokenSymbol]  means understanding the future, we need to learn more about this",
	"If you can keep talking about [TokenSymbol] I'm sure you will keep going higher in the level",
	"The pace of [TokenSymbol]'s depelopment is just right",
	"#[TokenSymbol] is just starting, we will see future depelopment soon",
	"Nothing more good than a wallet having an [TokenSymbol] in it",
	"It all depends on how much work we're willing to do for [TokenSymbol]",
	"[TokenSymbol] soon going to be every where in the world",
	"New day, new chance to support #[TokenSymbol]",
	"Guys, don't miss this big opportunity",
	"Just enjoy your time in here brother",
	"Togetherness we should support this project to the moon",
	"Keep your spirit you all, we can do this for [TokenSymbol]",
	"Keep doing what we are doing to support [TokenSymbol]",
	"I will always be in here full time to support [ProjectName]",
	"Let's go support for [TokenSymbol] more",
	"[ProjectName] is the future, we are in the early access of the future",
	"[TokenSymbol] will follow BTC's path, or create [TokenSymbol] own path. Let's go",
	"Shill for [TokenSymbol] more until reaach the moon",
	"Rocket for [TokenSymbol] to the mooon 🚀🚀",
	"Don't give up in supporting [TokenSymbol]",
	"Make [TokenSymbol] to be top 100 cryptos",
	"So many strong people in [TokenSymbol] community here",
	"We're moving forward with [TokenSymbol]",
	"Stick to the rules of [TokenSymbol] to make the community great guys",
	"Don't spam and keep meaningful message is the key",
	"Help each others here in [TokenSymbol]",
	"[ProjectName] whitepaper is best and looks cool",
	"[ProjectName]'s whitepaper is on another level",
	"Best project rely on best community",
	"It's never too late to support [TokenSymbol]",
	"Congratulations for everybody putting the best for [TokenSymbol]",
	"Tighten your seatbealt, [TokenSymbol] is gonna go to moon",
	"Thanks for [TokenSymbol] community, so many new things is here",
	"Sharing is the main foundation about what [ProjectName] see in the industry right now",
	"Always check the pinned message and the rules",
	"[TokenSymbol] feels like hidden gems on the internet",
	"[TokenSymbol] will make a many greatness in the future",
	"Keep your trust in [TokenSymbol] project",
	"This community is so great in developing a trust",
	"Trust in [TokenSymbol], [TokenSymbol] will trust you back",
	"Let's support [TokenSymbol] and each others here",
	"Follow [ProjectName] in every social media",
	"Don't force yourself, stay healthy",
	"Be the part of history of [TokenSymbol]",
	"HODL $[TokenSymbol] for the better future",
	"Let's invite more members for [TokenSymbol], let's go",
	"[TokenSymbol] good project with a strong community",
	"So many #[TokenSymbol] army here, you all are amazing",
	"Let's fly high with [TokenSymbol]",
	"Spread the greatness of [TokenSymbol] project",
	"Be ready for the rise of [TokenSymbol]",
	"[TokenSymbol] will hit $100 in the future or could be more",
	"Now or never, buy $[TokenSymbol] and hold it",
	"Always follow the [TokenSymbol] rules",
	"[TokenSymbol] will brings a change in global environment",
	"I have no doubt about [TokenSymbol] project",
	"All [TokenSymbol] information already written in the website",
	"It's a good opportunity for us to learn more about [TokenSymbol]",
	"[ProjectName] for the new token of the century",
	"We are proving that [TokenSymbol] have the best community",
	"Nothing impossible, [TokenSymbol] help you out with the great community",
	"Let's hope for the best of [TokenSymbol] here",
	"Be positive to everyone here in this community",
	"No pain no gain, you here in [TokenSymbol] for the win",
	"We're going to win this together and in a competitive way",
	"People who's not buy [TokenSymbol] will regret it a years later",
	"Let's go, push your level and win [TokenSymbol]",
	"I will support you if you need any",
	"I'm thankful to be able to know about [TokenSymbol]",
	"[TokenSymbol] is a hidden gem, no, it's diamond",
	"[TokenSymbol] here for me, and I here for [TokenSymbol]",
	"You all doing great until now",
	"#[TokenSymbol] to the moon and beyond",
	"Always turn on notification for [TokenSymbol]",
	"$[TokenSymbol] rocketing to the moon",
	"There's none other than [TokenSymbol] doing such a nice event to build a strong community by chatting",
	"Harvest your [TokenSymbol] in your staking pool",
	"Spread the love of [TokenSymbol] around the world",
	"Take a rest if you tired, comeback later",
	"[TokenSymbol] community is us and only us",
	"[TokenSymbol] moving to make a history",
	"Keep typing about [TokenSymbol] here don't give up",
	"A lot of people will start realizing how good is [TokenSymbol]",
	"Don't hesitate to invest in [TokenSymbol]",
	"Solid project of [TokenSymbol] with a great community inside of it",
	"I give my best to support this project",
	"[TokenSymbol] hit $100 is not impossible",
	"[TokenSymbol] moon soon, believe it or you regret later",
	"We're the part of [TokenSymbol] upcoming history",
	"Let's create a great history of [TokenSymbol]",
	"Don't waste your time for any others project",
	"You need [TokenSymbol] for the future",
	"[TokenSymbol] for the win all of us",
	"We're getting better and better as a community",
	"Nice project and I look forward to the growth and success of this project",
	"We are a very dedicated supporter of this project",
	"We can make [TokenSymbol] greater than it is now, I belive",
	"[TokenSymbol] is definitely showing the way to moon",
	"Let keep our hope very high and really ready for [TokenSymbol]",
	"Try your best in tweeting about [TokenSymbol] guys",
	"We are here to stay forever with [TokenSymbol]",
	"Tweet about [TokenSymbol] with all of your passion",
	"Lets hold [TokenSymbol] for a really long-term cause it worth it",
	"[ProjectName] has so much potential in future aspect",
	"Let's make [ProjectName] moon guys 🚀",
	"We all gonna win some token [TokenSymbol]",
	"If you're not winning [TokenSymbol] token, you're winning the knowledge about [TokenSymbol]",
	"Many knowledge was so gain here all the time",
	"When you see greatness, your only option is to follow. [TokenSymbol] is a greatness",
	"We are going to moon and mars with [TokenSymbol]",
	"I really really enjoying my time with [TokenSymbol] community",
	"Because #[TokenSymbol] we are here now",
	"I hope everyone believe in this project just like me",
	"[TokenSymbol] future is only getting better and better",
	"The dev really working hard for making [TokenSymbol] to the moon",
	"Go [ProjectName]! I know very well this project can be a dragon",
	"We're early accessing [TokenSymbol] and knowing the greatness of [TokenSymbol]",
	"One of the speciality of [ProjectName] is gathering a strong people to build a strong community",
	"[TokenSymbol] have a strong foundation that is the community",
	"We and [TokenSymbol] cannot be separated because we need each other",
	"[TokenSymbol] is making the right way for a better industrial revolution",
	"Doubting this project is out of my thoughts",
	"Lets support [TokenSymbol] while we can here with a full power",
	"[TokenSymbol] is here to help you achieve a bright future",
	"[TokenSymbol] definitely a good project and wrapped a strong community",
	"This project could be the greatest project in crypto history",
	"We should learn from [TokenSymbol] how this project view a world's problems",
	"We should start investing in this project for our family, future and our child",
	"I have no doubt in trusting this [TokenSymbol] project",
	"Keep typing and keep up a good work for [TokenSymbol]",
	"You will gain what you give for [TokenSymbol]",
	"[TokenSymbol] is a masterpiece in a blockchain",
	"Do your best to support [TokenSymbol]",
	"We are different, but are goal are the same for supporting [TokenSymbol]",
	"Do your own way to support [TokenSymbol]",
	"Never doubting the greatness of this project",
	"Lets expand this community to be more big",
	"Don't get distracted by other projects, [TokenSymbol] is way more clear in visualing the future",
	"Im thankful to be born and know the [TokenSymbol] project",
	"Don't miss this opportunity with [TokenSymbol]",
	"Im full excitement to see [TokenSymbol] in the future",
	"Trusting [TokenSymbol] is like trusting your future to be bright",
	"[TokenSymbol] soldiers never stop supporting [TokenSymbol]",
	"At this point, you should realize how good this project is",
	"All thanks to [TokenSymbol] for the event that we can know more about this unbelievable good project",
	"We can't change the past, let's repair our earth and prepare it with [TokenSymbol]",
	"Spend more time with [TokenSymbol] to gain better understandanding of the porject",
	"I understand how strong this community has become",
	"No need to tell how strong [TokenSymbol] community is, it's amazingly strong",
	"You're not wrong choosing to focus in [TokenSymbol] project",
	"Tweet [TokenSymbol] more and show the world with your words",
	"We're [TokenSymbol]'s front lines in journey to the future",
	"Take a rest if you're tired, [TokenSymbol] need to be supported with your best health condition",
	"It's kind of sad for those who haven't know about [TokenSymbol] project",
	"[TokenSymbol] is solid and interesting project to follow",
	"The dev is working really hard I guess",
	"The fact that we see a quality in this project, the dev must be a bunch of quality person",
	"Next year [TokenSymbol] is globally available, I hope",
	"We are ready to face the future as long we hold the [TokenSymbol]",
	"[TokenSymbol] is great and a project with full of potential. Noted",
	"Supporting people here is supporting the community",
	"Hold [TokenSymbol], close your eyes and open it, you will see the future",
	"Now or never, support this project or you regret it in the future",
	"More than thousand collaboration [TokenSymbol] in the future",
	"Don't miss this great project, 👍",
	"Continue the flow of support for [TokenSymbol]",
	"Nothing is impossible, [TokenSymbol] is the way to solve your problem",
	"Concrete plan by [TokenSymbol] project for the future",
	"Gather your power to support [TokenSymbol] at full power",
	"[TokenSymbol] will made a big contribution in the world",
	"A lot of positivity in [TokenSymbol] community, I love it",
	"[ProjectName] provides an introduction with many new terms",
	"We all know that [ProjectName] project is amazing",
	"Our dream is [ProjectName] can go to the moon with us",
	"[ProjectName] is going to be best project on decade",
	"[ProjectName] is filling energy to Moon🚀",
	"Let's bring moon closer with the power of [TokenSymbol]",
	"[ProjectName] is a great to investment in the future",
	"I'm waiting [TokenSymbol] to have a global partner",
	"We will make [ProjectName] on every planet not just moon",
	"Dedicate all of your effort here for [TokenSymbol]",
	"The whole world will be amazed by [ProjectName]",
	"[TokenSymbol] community as a strong team are like solid diamond",
	"Let's keep moving forward for $[TokenSymbol]",
	"I'm trying to doing my best for this marvelous project",
	"Everyone has the right to be happy because they were met by [ProjectName]",
	"We are united here and known as [ProjectName] family",
	"Golden moment soon come to [ProjectName]",
	"Keep up with the good work in [TokenSymbol] guys",
	"We gain many knowledge here everyday",
	"Transparency is a important, and [TokenSymbol] does really well",
	"[ProjectName] will fly because the ecosystem is start getting better",
	"We see a bright prospect in [ProjectName] project",
	"We have to support each other as a family",
	"[ProjectName] will lead us to bright future",
	"This is a project where you should invite your family and friends to invest in",
	"We gain so many knowledge here every single day and",
	"We need to learn all [TokenSymbol] information here and spread it to others",
	"I really liked this [TokenSymbol] community, it's so friendly",
	"We need to focus to learn about [TokenSymbol] and directed for always support [TokenSymbol]",
	"The community event is a positive thing for the development of [ProjectName]",
	"Always stick to [ProjectName] Official Chat rules",
	"This is a good chance to make [ProjectName] more familiar for everyone",
	"Learning and supporting [TokenSymbol] for our better future",
	"Keep your focus, learn everything here, and support each other to make [TokenSymbol] more great",
];
